services:
#    pg_gsb_frais.example:
#        class: Pg\GsbFraisBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    pg_gsb_frais.pdo:
        class: Pg\GsbFraisBundle\services\PdoGsb
        arguments: ["mysql:host=localhost", "dbname=gsb_frais", "userGsb","secret"]
